config/routes.rb
Todos::Application.routes.draw do
  devise_for :users,
             :path => '',
             :path_names => { sign_in:  "login",
                              sign_out: "logout",
                              sign_up:  "register" }

  root :to => 'todos#index'

  get '/user/todos', to: 'users#todos'
  get '/export', to: 'export#export'
  get '/todos/json', to: 'todos#json', defaults: { format: 'json' }

  resources :todos do
    resources :tasks, only: [:new, :edit, :create, :update, :destroy]
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :content, :todo_id, :finished
  validates :content, presence: true

  belongs_to :todo
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :title, :private, :tasks_attributes
  validates :title, presence: true

  belongs_to :user
  has_many :tasks
  accepts_nested_attributes_for :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def json_helper(todos, total_todos)
    if params[:sSearch].present?
      todos = todos_search(todos)
    end

    todos = todos.joins(:user).order("#{sort_column} #{sort_order}")

    render_json(todos, total_todos)
  end

  def todos_search(todos)
    todos.where('LOWER(todos.title) LIKE :search OR LOWER(users.name) LIKE :search', search: "%#{params[:sSearch]}%".downcase)
  end

  def render_json(todos, total_todos)
    todos_json = {}
    todos_json[:sEcho] = params[:sEcho].to_i
    todos_json[:iTotalRecords] = todos.count
    todos_json[:iTotalDisplayRecords] = total_todos

    todos_json[:aaData] = todos.map do |todo|
      [todo.title, todo.user.name, todo.created_at.strftime("%d %b %Y"), todo_path(todo)]
    end

    todos_json
  end

  def sort_column
    columns = %w[todos.title users.name todos.created_at]
    columns[params[:iSortCol_0].to_i]
  end

  def sort_order
    params[:sSortDir_0] == "desc" ? "DESC" : "ASC"
  end
end

app/controllers/export_controller.rb
class ExportController < ApplicationController
  before_filter :authenticate_user!

  def export
    @user_todos = current_user.todos
    @public_todos = Todo.where("user_id != ? AND private=false", current_user)

    # Setup Axlsx (cuz it's cool)
    p = Axlsx::Package.new
    wb = p.workbook

    # Add some styles
    wb.styles do |s|
      heading = s.add_style bg_color: "33", fg_color: "FF", sz: 13, alignment: {horizontal: :center}
      todo_heading = s.add_style bg_color: "66", fg_color: "FF", sz: 12

      # Add the data
      wb.add_worksheet(name: "Todos") do |sheet|
        list_todos(@user_todos, heading, sheet, todo_heading)
        list_todos(@public_todos, heading, sheet, todo_heading)
      end
    end

    # Download the file
    p.serialize('tmp/todos.xlsx')
    send_file('tmp/todos.xlsx')
  end

  private

  def list_todos(todos_list, heading, sheet, todo_heading)
    todos_list.each do |todo|
      # Todos Title
      sheet.add_row ["Title", "User", "Private"], style: heading
      sheet.add_row [todo.title, todo.user.name, status?(todo.private)]

      spacer(sheet, 1) # add 1 empty row

      # Tasks
      sheet.add_row ["Content", "Finished?"], style: todo_heading
      todo.tasks.each do |task|
        sheet.add_row [task.content, status?(task.finished)]
      end

      spacer(sheet)
    end
  end

  def spacer(sheet, size=2)
    size.times do
      sheet.add_row [""] # Empty row
    end
  end

  def status?(status)
    status ? "Yes" : "No"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    todo = Todo.find(params[:todo_id])
    @task = todo.tasks.create(params[:task])

    if @task.save
      flash[:success] = 'New task added!'
      redirect_to @task.todo
    end
  end

  def update
    @todo = Todo.find(params[:todo_id])
    @task = Task.find(params[:id])
    @task.finished = !@task.finished

    @task.save

    redirect_to @todo
  end

  def destroy
    task = Task.find(params[:id])

    if task.todo.user == current_user
      task.destroy
    end

    redirect_to task.todo
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :new, :update]

  def index
    @todos_source = todos_json_path
    @todos = Todo.where private: false

    respond_to do |format|
      format.html
      format.json { render json: json_handler }
    end
  end

  def json_handler
    todos = Todo.where(private: false)
    todos_total = todos.count

    todos = todos.limit(params[:iDisplayLength].to_i)
                 .offset(params[:iDisplayStart])

    json_helper(todos, todos_total)
  end

  def new
    @todo = Todo.new
    @todo.tasks.build
  end

  def show
    @todo = Todo.find(params[:id])

    if user_signed_in?
      @task = Task.new
    end

    if @todo.user == current_user
      @todo_private_toggle_label = @todo.private ? 'Set public' : 'Set private'
    end

    if @todo.private? and @todo.user != current_user
      redirect_to root_path
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = current_user.todos.build(params[:todo])

    if @todo.save
      flash[:success] = "Todo created!"
      redirect_to @todo
    else
      render 'todos/new'
    end
  end

  def update
    todo = Todo.find(params[:id])
    todo.private = !todo.private
    todo.save

    redirect_to todo
  end

  def destroy
    todo = Todo.find(params[:id])

    if todo.user == current_user
      todo.destroy
    end

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json_handler

  def profile
    if user_signed_in?
      render 'users/profile'
    else
      redirect_to root_path
    end
  end

  def todos
    @todos = current_user.todos.limit(10)
    @todos_source = user_todos_path

    respond_to do |format|
      format.html
      format.json { render json: json_handler }
    end
  end

  def json_handler
    todos = current_user.todos
    todos_total = todos.count

    todos = todos.limit(params[:iDisplayLength].to_i)
                 .offset(params[:iDisplayStart])

    json_helper(todos, todos_total)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Todos App", root_path, class: "brand" %>

      <div class="nav-collapse collapse" style="height: 0px;">
        <ul class="nav pull-right">
          <li class="active"><%= link_to "Home", root_path %></li>

          <% if signed_in? %>
              <li><%= link_to "Export all", export_path %></li>
              <li><%= link_to "New Todo", new_todo_path %></li>
              <li><%= link_to "My Todos", user_todos_path %></li>
              <li> <%= link_to "Sign out", destroy_user_session_path %></li>
          <% else %>
              <li><%= link_to "Register", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container"><%= yield %></div>

</body>
</html>

app/views/partials/_todos-list.html.erb
<div class="page-header">
  <h1>Todos</h1>
</div>

<table class="table table-striped datatable-todos" data-source="<%= @todos_source %>">
  <thead>
    <tr>
      <th>Title</th>
      <th>Owner</th>
      <th>Created Date</th>
    </tr>
  </thead>
  <tbody></tbody>
</table>

app/views/todos/index.html.erb
<h1>This is the homepage</h1>

<h3>Tasks</h3>

<ul>
  <% @todos.each do |todo| %>
    <li><%= link_to todo.title, todo %>, Owner: <%= todo.user.name %></li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<div class="page-header"><h1>Create todo</h1></div>

<%= simple_form_for(@todo, :html => {:class => 'form-vertical' }) do |f| %>
    <%= f.input :title %>

    <%= f.simple_fields_for :tasks do |task| %>
        <%= task.input :content, label: "Task" %>
    <% end %>

    <%= f.input :private, label: false, inline_label: "Private" %>

    <div class="control-group">
      <div class="controls">
        <%= f.button :submit %>
      </div>
    </div>
<% end %>

app/views/todos/show.html.erb
<div class="page-header">
  <h1><%= @todo.title %></h1>

  <div>by <%= @todo.user.name %></div>
</div>

<% if current_user == @todo.user %>
    <h4>Options</h4>

    <div class="toggle-privacy-form options">
      <%= button_to @todo_private_toggle_label, @todo, :method => :put %>
      <%= button_to "delete", @todo, :method => :delete %>
    </div>
<% end %>

<h4>Tasks</h4>

<% if @todo.tasks.empty? %>
    No tasks made yet...
<% else %>
    <table class="table table-striped datatable-tasks">
      <thead>
        <tr>
          <th>Task</th>
          <% if current_user == @todo.user %>
              <th>Options</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @todo.tasks.each do |task| %>
            <tr>
              <% if task.finished? %>
                  <td class="finished"><%= task.content %></td>
              <% else %>
                  <td><%= task.content %></td>
              <% end %>


              <% if current_user == @todo.user %>
                  <td class="options">
                    <%= button_to "delete", todo_task_path(@todo, task), :method => :delete %>
                    <%= button_to "toggle finished", todo_task_path(@todo, task), :method => :put %>
                  </td>
              <% end %>
            </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

<% if current_user == @todo.user %>
    <div class="add-task-form">
      <h4>Add a new task</h4>

      <%= simple_form_for @task, url: todo_tasks_path(@todo) do |f| %>
          <%= f.input :content, label: "Task" %>
          <%= f.button :submit %>
      <% end %>
    </div>
<% end %>

app/views/users/profile.html.erb
<div class="page-header"><h1>Edit Profile</h1></div>

<%= simple_form_for current_user do |f| %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

    <%= f.button :submit %>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/todos.html.erb
<%= render 'partials/todos-list' %>